spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:42543/railway
    username: postgres
    password: aIdufoKaiPUafnzUzxjpnwfqysyvrEpl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /api/v1
project:
  house: house/
  profile: profile/
base:
  url: "http://sakan-production-5ec7.up.railway.app/api/v1"
